apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-backend-deployment
  template:
    metadata:
      labels:
        app: bank-backend-deployment
    spec:
      serviceAccountName: bank-app-ksa
      containers:
      - name: bank-backend-container
        image: us-central1-docker.pkg.dev/development-423908/bank-repo/bank-app@sha256:ffb1382a8daf8470b355707ac94f9c08efc66b29e4be1a3d536bf2a7e93ac0e2
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bank-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: bank-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: bank-config
              key: DB_NAME

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: bank-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bank-secret
              key: DB_PASSWORD          
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "300m"      
